#+title: plan-polsl.el
#+author: Szymon Wilczek
#+email: swilczek.lx@gmail.com
#+language: pl
#+startup: overview

[[https://www.gnu.org/software/emacs/][https://img.shields.io/badge/Emacs-28.1+-blueviolet.svg?style=flat-square&logo=gnu-emacs&logoColor=white]]
[[https://www.gnu.org/licenses/gpl-3.0][https://img.shields.io/badge/License-GPLv3-blue.svg?style=flat-square]]

*plan-polsl.el* to pakiet dla GNU Emacsa integrujący oficjalny system planów zajęć *Politechniki Śląskiej* ([[https://plan.polsl.pl/][plan.polsl.pl]]) dla grup studenckich, nauczycieli akademickich i sal z *Org-mode*, *Org-Agenda* oraz dedykowanym podglądem w buforze pamięci.

Pobiera plan bezpośrednio z serwerów uczelni, parsuje współrzędne siatki godzinowej, sal i grup/sekcji, wyświetla go w dedykowanym buforze ~*Plan PolSL*~ oraz synchronizuje z kalendarzem Org-Agenda.

* Możliwości

- *Dedykowany podgląd w pamięci (~M-x plan-polsl~):* Natychmiastowe przeglądanie sformatowanego planu w buforze ~*Plan PolSL*~ o szerokości 65% z klawiszami:
  - ~q~ : Zamknij bufor
  - ~r~ : Odśwież plan z serwera
  - ~s~ : Synchronizuj z Org-Agenda
  - ~<~ / ~>~ : Nawigacja między tygodniami (poprzedni / następny tydzień)
- *Domyślny widok bieżącego tygodnia:* Automatyczne dopasowanie do bieżącego tygodnia akademickiego (tydzień parzysty/nieparzysty) z dokładnymi datami kalendarzowymi.
- *Błyskawiczne wyszukiwanie (~M-x plan-polsl-search~):*
  - *Nauczyciele:* Natychmiastowe wyszukiwanie po nazwisku z podpowiedziami spośród wszystkich pracowników uczelni.
  - *Grupy i sale:* Nawigacja po strukturze drzewiastej (Wydział -> Kierunek -> Semestr -> Grupa).
- *Wsparcie dla grup studenckich, nauczycieli i sal:* Obsługa endpointów grup (~type=0~), nauczycieli (~type=10~) oraz sal (~type=20~).
- *Bezpośrednia integracja z plan.polsl.pl:* Pobiera i parsuje układ planu w locie przy użyciu wbudowanego silnika ~libxml/dom~.
- *Inteligentne znaczniki powtarzalności:* Zakotwicza terminy w dacie startu semestru akademickiego, dzięki czemu w wakacje Org-Agenda jest całkowicie czysta.
- *Automatyczna rejestracja w Org-Agenda:* Wygenerowany plik jest automatycznie dodawany do ~org-agenda-files~.

* Konfiguracja (use-package)

Wszystkie parametry konfiguruje się bezpośrednio w definicji pakietu w Emacsie:

#+begin_src elisp
  (use-package plan-polsl
    :load-path "~/Dokumenty/GitHub/plan-polsl.el"
    :commands (plan-polsl plan-polsl-sync plan-polsl-open-plan plan-polsl-search)
    :custom
    (plan-polsl-id "343266256")                                    ;; ID grupy lub nauczyciela z plan.polsl.pl
    (plan-polsl-type 0)                                            ;; 0 = grupa studencka, 10 = nauczyciel, 20 = sala
    (plan-polsl-target-file "~/Dokumenty/writings/plan-polsl.org") ;; Ścieżka docelowa pliku Org
    (plan-polsl-auto-add-to-agenda t))                             ;; Dodaj do Org-Agenda
#+end_src

* Komendy interaktywne

| Komenda                  | Opis                                                                                                       |
|--------------------------+------------------------------------------------------------------------------------------------------------|
| ~M-x plan-polsl~           | Otwiera dedykowany bufor ~*Plan PolSL*~ z podglądem planu skonfigurowanego w ~plan-polsl-id~.                  |
| ~M-x plan-polsl-search~    | Interaktywne wyszukiwanie planu dowolnej grupy, nauczyciela lub sali przez nawigację po drzewie wydziałów. |
| ~M-x plan-polsl-sync~      | Pobiera i aktualizuje plan do pliku Org-mode dla Org-Agenda.                                               |
| ~M-x plan-polsl-open-plan~ | Otwiera wygenerowany plik ~plan-polsl.org~.                                                                  |

* Autor & Licencja

- *Autor:* Szymon Wilczek
- *Licencja:* [[file:LICENSE][GNU General Public License v3.0 (GPLv3)]]
  
